### ISSUE TITLE
Please add English or Spanish language.

### ISSUE THREAD

**Issue by helpmebro911** [pyadrus/TelegramMaster-2.0#46]
Please add English or Spanish language.

**Comment by pyadrus** [comment]
At the moment, there is no time for localization, as well as for funds to localize to other languages, except for Russian.

**Comment by helpmebro911** [comment]
I can make a donation and help you with the translation.

**Comment by pyadrus** [comment]
Write https://t.me/PyAdminRU Let's discuss it in more detail.
