### ISSUE TITLE
Полезная функция

### ISSUE THREAD

**Issue by Fire285** [pyadrus/TelegramMaster-2.0#49]
Просьба добавить при парсинге активных пользователей возможность группировки спарсеных пользователей по подфорумам
для подобных групп 
https://t.me/mdf_official
подфорумы вида
https://t.me/mdf_official/271169
https://t.me/mdf_official/1
https://t.me/mdf_official/230313
и так далее

**Comment by pyadrus** [comment]
Довольно интересная задумка, и можно добавить в дорожную карту для дальнейшего развития. Данный подход может сильно поменять общую сложившуюся концепцию работы с программой и в общем целом отразится на пользовательском опыте, так как работать с программой станет сложнее. 

На данный момент идея в том, что пользователь парсит группы, и всё пишется в одну базу данных (в одну таблицу), и с этой базы может выполнять дальнейшие действия, такие как: инвайтинг, парсинг, рассылка сообщений и так далее. Если реализовать функцию, которую вы хотите, то пользователю придется помимо парсинга еще и отдельно формировать списки со спарсенными данными. 

В общем целом получается такой вариант: у пользователя будет больше функций, и появится еще больше проблем с работой программы. 

При добавлении каждой новой функции нужно учитывать еще тот момент, что программой пользуются и абсолютные новички, и у каждого уровень разный. Для многих слово «Документация» — это что-то из разряда уровня «Мидл +».

**Comment by helpmebro911** [comment]
Думаю можно сделать это опционально пользователь ставит галочку и тогда все парситься по разделам .
если галочки нет все общим списком.

**Comment by Fire285** [comment]
Думаю можно сделать это опционально пользователь ставит галочку и тогда все парситься по разделам .
если галочки нет все общим списком

**Comment by helpmebro911** [comment]
> Думаю можно сделать это опционально пользователь ставит галочку и тогда все парситься по разделам, если галочки нет все общим списком

thank you, you make software that is useful for beginners.
Although I have to use a translator.

**Comment by helpmebro911** [comment]
> Довольно интересная задумка, и можно добавить в дорожную карту для дальнейшего развития. Данный подход может сильно поменять общую сложившуюся концепцию работы с программой и в общем целом отразится на пользовательском опыте, так как работать с программой станет сложнее.
> 
> На данный момент идея в том, что пользователь парсит группы, и всё пишется в одну базу данных (в одну таблицу), и с этой базы может выполнять дальнейшие действия, такие как: инвайтинг, парсинг, рассылка сообщений и так далее. Если реализовать функцию, которую вы хотите, то пользователю придется помимо парсинга еще и отдельно формировать списки со спарсенными данными.
> 
> В общем целом получается такой вариант: у пользователя будет больше функций, и появится еще больше проблем с работой программы.
> 
> При добавлении каждой новой функции нужно учитывать еще тот момент, что программой пользуются и абсолютные новички, и у каждого уровень разный. Для многих слово «Документация» — это что-то из разряда уровня «Мидл +».

thank you, you make software that is useful for beginners.
Although I have to use a google translate.

**Comment by pyadrus** [comment]
@Fire285, возможно, для вас это и просто, но новым пользователям это будет не сильно просто. 

Так как я параллельно написания и поддержки программы параллельно пишу и документацию по работе с программой, и я не вижу данную функцию как простую. Можно до бесконечности пилить новый функционал к программе, но также необходимо писать и документацию. 

Ваша идея хорошая, но я не побегу ее сразу делать, так как кому-то просто захотелось. Есть более важные задачи. Если вы хотите, то можете подключиться к развитию проекта. Напишите в ТГ https://t.me/PyAdminRU, всё обсудим.

**Comment by pyadrus** [comment]
> > Довольно интересная задумка, и можно добавить в дорожную карту для дальнейшего развития. Данный подход может сильно поменять общую сложившуюся концепцию работы с программой и в общем целом отразится на пользовательском опыте, так как работать с программой станет сложнее.
> > На данный момент идея в том, что пользователь парсит группы, и всё пишется в одну базу данных (в одну таблицу), и с этой базы может выполнять дальнейшие действия, такие как: инвайтинг, парсинг, рассылка сообщений и так далее. Если реализовать функцию, которую вы хотите, то пользователю придется помимо парсинга еще и отдельно формировать списки со спарсенными данными.
> > В общем целом получается такой вариант: у пользователя будет больше функций, и появится еще больше проблем с работой программы.
> > При добавлении каждой новой функции нужно учитывать еще тот момент, что программой пользуются и абсолютные новички, и у каждого уровень разный. Для многих слово «Документация» — это что-то из разряда уровня «Мидл +».
> 
> thank you, you make software that is useful for beginners. Although I have to use a google translate.

As I wrote to you earlier. At the moment, there is no time for localization, as well as funds for localization into other languages other than Russian. I am working on a project alone, this project does not generate income so that I can fully devote time to it and deal only with this project. If you want to help in the development of the project, then write to Telegram https://t.me/PyAdminRU .
