### ISSUE TITLE
Автоответчик и прокси.

### ISSUE THREAD

**Issue by en58** [pyadrus/TelegramMaster-2.0#50]
Поддерживает ли софт мтпрокси и автоответчик с gpt?

было бы полезно добавить нейро комментинг в комментариях.

**Comment by pyadrus** [comment]
Функции с ИИ будут внедряться после Нового года. MTProxy на данный момент не поддерживается и внедрение не планируется. Возможно, в будущем я добавлю данную функцию, но на данный момент данная функция не в приоритете.

**Comment by helpmebro911** [comment]
Спасибо за ответ
Тогда еще было бы круто добавить нейро ботов для комментариев рассылок.

**Comment by helpmebro911** [comment]
chatgpt - this good!!!

**Comment by pyadrus** [comment]
Возможно, когда-то сделаю. Желающих тьма, пожеланий тоже, но помощи и поддержки 0. Поэтому я веду развитие проекта по своему намеченному плану.
